#!/bin/bash


USAGE="$0 DIRNAME HOSTNAME PLAYER_A PLAYER_B"
EXAMPLE="$0 petrov-tempdir-3433 123.45.67.89 Seattle:seattle-password Oxford:oxford-password    to run the code in ~/petrov-tempdir-3433 with players Seattle and Oxford, generating urls like http://123.45.67.89/seattle-password"

bad-usage() {
    echo "$@" >&2
    echo "Usage: $USAGE" >&2
    echo "Example: $EXAMPLE" >&2
    exit 1
}

[ "$#" = 4 ] || bad-usage 'wrong number of arguments'
DIRNAME=$1; shift; [ -n "$DIRNAME" ] || bad-usage "DIRNAME must not be empty"
HOSTNAME=$1; shift; [ -n "$HOSTNAME" ] || bad-usage "HOSTNAME must not be empty"
PLAYER_A=$1; shift; [ -n "$PLAYER_A" ] || bad-usage "PLAYER_A must not be empty"
PLAYER_B=$1; shift; [ -n "$PLAYER_B" ] || bad-usage "PLAYER_B must not be empty"

set -e
set -x

cd ~/$DIRNAME

netstat -tlnp | grep -q :2344 && pkill go
screen go run main.go \
       -players="$PLAYER_A,$PLAYER_B" \
       -hostname="$HOSTNAME" \
       -GameDuration=2h30m \
       -MissileFlightTime=15m \
       -MeanFalseAlarmInterval=60m
