#!/bin/bash

set -e
set -x

DIRNAME=$1
HOSTNAME=$2
cd ~/$DIRNAME

netstat -tlnp | grep -q :2344 && pkill go
screen go run main.go \
       -players="Seattle,Oxford" \
       -hostname=$HOSTNAME \
       -GameDuration=3h \
       -MissileFlightTime=15m \
       -MeanFalseAlarmInterval=60m
