#!/bin/bash


USAGE="$0 DIRNAME HOSTNAME PLAYER_A PLAYER_B"
EXAMPLE="$0 petrov-tempdir-3433 123.45.67.89 Seattle:seattle-password Oxford:oxford-password    to run the code in ~/petrov-tempdir-3433 with players Seattle and Oxford, generating urls like http://123.45.67.89/seattle-password"

bad-usage() {
    echo "$@" >&2
    echo "Usage: $USAGE" >&2
    echo "Example: $EXAMPLE" >&2
    exit 1
}

[ "$#" = 4 ] || bad-usage 'wrong number of arguments'
DIRNAME=$1; shift
HOSTNAME=$1; shift
PLAYER_A=$1; shift
PLAYER_B=$2; shift

set -e
set -x

cd ~/$DIRNAME

netstat -tlnp | grep -q :2344 && pkill go
screen go run main.go \
       -players="$PLAYER_A,$PLAYER_B" \
       -hostname="$HOSTNAME" \
       -GameDuration=2h30m \
       -MissileFlightTime=15m \
       -MeanFalseAlarmInterval=60m
