#!/bin/bash
# Run me from your laptop.

set -e
set -x

USER=petrov
HOSTNAME=192.151.146.250
DIRNAME=petrov-deploy-$$

git clone git@github.com:speezepearson/petrov.git /tmp/$DIRNAME
rsync -avz --delete /tmp/$DIRNAME $USER@$HOSTNAME:
ssh -t $USER@$HOSTNAME ./$DIRNAME/ops/internal/run-game $DIRNAME
