#!/bin/bash
# Run me from your laptop.

USAGE="$0 PETROV_USER PETROV_HOSTNAME PLAYER_A PLAYER_B"
EXAMPLE="$0 petrov 123.45.67.89 Seattle:seattle-password Oxford:oxford-password    to run a Seattle-vs-Oxford game as petrov@123.45.67.89"

bad-usage() {
    echo "$@" >&2
    echo "Usage: $USAGE" >&2
    echo "Example: $EXAMPLE" >&2
    exit 1
}

[ "$#" = 4 ] || bad-usage "wrong number of arguments (got $#, expected 4)"
PETROV_USER=$1; shift; [ -n "$PETROV_USER" ] || bad-usage "PETROV_USER must not be empty"
PETROV_HOSTNAME=$1; shift; [ -n "$PETROV_HOSTNAME" ] || bad-usage "PETROV_HOSTNAME must not be empty"
PLAYER_A=$1; shift; [ -n "$PLAYER_A" ] || bad-usage "PLAYER_A must not be empty"
PLAYER_B=$1; shift; [ -n "$PLAYER_B" ] || bad-usage "PLAYER_B must not be empty"

set -e
set -x

DIRNAME="petrov-deploy-$$"

git clone --depth 1 https://github.com/speezepearson/petrov.git "/tmp/$DIRNAME"
rsync -avz --delete "/tmp/$DIRNAME" "$PETROV_USER@$PETROV_HOSTNAME:"
ssh -t "$PETROV_USER@$PETROV_HOSTNAME" "./$DIRNAME/ops/internal/run-game" "$DIRNAME" "$PETROV_HOSTNAME" "$PLAYER_A" "$PLAYER_B"
